# Generated by Django 4.2.4 on 2023-08-26 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availabe',
            field=models.BooleanField(default=True),
        ),
    ]
